ENVIRONMENT=development
BASE_URL_DEV=https://reqres.in
BASE_URL_STAGING=https://staging.reqres.in
BASE_URL_PROD=https://prod.reqres.in
API_KEY=reqres-free-v1
SMOKE_USERS=1
SMOKE_RAMPUP=1
LOAD_USERS=50
LOAD_RAMPUP=60
LOAD_ITERATIONS=10
STRESS_USERS=200
STRESS_RAMPUP=120
SPIKE_USERS=500
SPIKE_RAMPUP=10
THINK_TIME_MIN=1000
THINK_TIME_MAX=3000
P99_THRESHOLD=2000
P95_THRESHOLD=1000
P90_THRESHOLD=500
ERROR_RATE_THRESHOLD=5
SOAK_USERS=20
SOAK_RAMPUP=30
SOAK_DURATION=3600
