jmeter.backend_listener.mongodb=false
jmeter.save.saveservice.output_format=csv
jmeter.save.saveservice.assertion_results_failure_message=true
jmeter.save.saveservice.assertion_results=true
jmeter.save.saveservice.data_type=true
jmeter.save.saveservice.label=true
jmeter.save.saveservice.response_code=true
jmeter.save.saveservice.response_data.on_error=true
jmeter.save.saveservice.response_message=true
jmeter.save.saveservice.successful=true
jmeter.save.saveservice.thread_name=true
jmeter.save.saveservice.time=true
jmeter.save.saveservice.subresults=true
jmeter.save.saveservice.assertions=true
jmeter.save.saveservice.latency=true
jmeter.save.saveservice.connect_time=true
jmeter.save.saveservice.samplerData=true
jmeter.save.saveservice.responseHeaders=true
jmeter.save.saveservice.requestHeaders=true
jmeter.save.saveservice.encoding=true
jmeter.save.saveservice.bytes=true
jmeter.save.saveservice.sent_bytes=true
jmeter.save.saveservice.url=true
jmeter.save.saveservice.thread_counts=true
jmeter.save.saveservice.idle_time=true
summary.report.name=Performance Test Summary Report
aggregate_rampup_graph_module_statistics_visible_range_max=300000
aggregate_rampup_graph_module_statistics_visible_range_min=0
response_time_percentiles=50,75,90,95,99
sampleresult.default.encoding=UTF-8
sampleresult.timestamp.start=true
httpsampler.max_redirects=10
httpsampler.max_frame_depth=5
httpclient.timeout=60000
httpclient.socket.timeout=60000
